# Generated by Django 2.0.1 on 2018-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('visible_to_owner', models.BooleanField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
